//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_VIA_Cinema.ViaPayServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ViaPayServiceReference.IViaPayService")]
    public interface IViaPayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViaPayService/MakeTransaction", ReplyAction="http://tempuri.org/IViaPayService/MakeTransactionResponse")]
        bool MakeTransaction(string creditCardNumber, string pin, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViaPayService/MakeTransaction", ReplyAction="http://tempuri.org/IViaPayService/MakeTransactionResponse")]
        System.Threading.Tasks.Task<bool> MakeTransactionAsync(string creditCardNumber, string pin, decimal amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IViaPayServiceChannel : WebApplication_VIA_Cinema.ViaPayServiceReference.IViaPayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViaPayServiceClient : System.ServiceModel.ClientBase<WebApplication_VIA_Cinema.ViaPayServiceReference.IViaPayService>, WebApplication_VIA_Cinema.ViaPayServiceReference.IViaPayService {
        
        public ViaPayServiceClient() {
        }
        
        public ViaPayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViaPayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViaPayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViaPayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool MakeTransaction(string creditCardNumber, string pin, decimal amount) {
            return base.Channel.MakeTransaction(creditCardNumber, pin, amount);
        }
        
        public System.Threading.Tasks.Task<bool> MakeTransactionAsync(string creditCardNumber, string pin, decimal amount) {
            return base.Channel.MakeTransactionAsync(creditCardNumber, pin, amount);
        }
    }
}
