//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private System.DateTime BirthdayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ViaCinemaUserService.ViaCinemaUserServiceSoap")]
    public interface ViaCinemaUserServiceSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginResponse Login(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginResponse> LoginAsync(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAccount", ReplyAction="*")]
        DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountResponse CreateAccount(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountResponse> CreateAccountAsync(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequest request);
        
        // CODEGEN: Generating message contract since element name userEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserExists", ReplyAction="*")]
        DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsResponse UserExists(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserExists", ReplyAction="*")]
        System.Threading.Tasks.Task<DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsResponse> UserExistsAsync(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string email, string userPassword) {
            this.email = email;
            this.userPassword = userPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccount", Namespace="http://tempuri.org/", Order=0)]
        public DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequestBody Body;
        
        public CreateAccountRequest() {
        }
        
        public CreateAccountRequest(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int dayOfBirth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int monthOfBirth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int yearOfBirth;
        
        public CreateAccountRequestBody() {
        }
        
        public CreateAccountRequestBody(string email, string userPassword, string firstName, string lastName, int dayOfBirth, int monthOfBirth, int yearOfBirth) {
            this.email = email;
            this.userPassword = userPassword;
            this.firstName = firstName;
            this.lastName = lastName;
            this.dayOfBirth = dayOfBirth;
            this.monthOfBirth = monthOfBirth;
            this.yearOfBirth = yearOfBirth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountResponseBody Body;
        
        public CreateAccountResponse() {
        }
        
        public CreateAccountResponse(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserAccount CreateAccountResult;
        
        public CreateAccountResponseBody() {
        }
        
        public CreateAccountResponseBody(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserAccount CreateAccountResult) {
            this.CreateAccountResult = CreateAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserExists", Namespace="http://tempuri.org/", Order=0)]
        public DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequestBody Body;
        
        public UserExistsRequest() {
        }
        
        public UserExistsRequest(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userEmail;
        
        public UserExistsRequestBody() {
        }
        
        public UserExistsRequestBody(string userEmail) {
            this.userEmail = userEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserExistsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsResponseBody Body;
        
        public UserExistsResponse() {
        }
        
        public UserExistsResponse(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UserExistsResult;
        
        public UserExistsResponseBody() {
        }
        
        public UserExistsResponseBody(bool UserExistsResult) {
            this.UserExistsResult = UserExistsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ViaCinemaUserServiceSoapChannel : DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViaCinemaUserServiceSoapClient : System.ServiceModel.ClientBase<DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap>, DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap {
        
        public ViaCinemaUserServiceSoapClient() {
        }
        
        public ViaCinemaUserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViaCinemaUserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViaCinemaUserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViaCinemaUserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginResponse DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap.Login(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string email, string userPassword) {
            DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequest inValue = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequest();
            inValue.Body = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.userPassword = userPassword;
            DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginResponse retVal = ((DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginResponse> DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap.LoginAsync(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginResponse> LoginAsync(string email, string userPassword) {
            DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequest inValue = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequest();
            inValue.Body = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.userPassword = userPassword;
            return ((DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountResponse DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap.CreateAccount(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequest request) {
            return base.Channel.CreateAccount(request);
        }
        
        public DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserAccount CreateAccount(string email, string userPassword, string firstName, string lastName, int dayOfBirth, int monthOfBirth, int yearOfBirth) {
            DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequest inValue = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequest();
            inValue.Body = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequestBody();
            inValue.Body.email = email;
            inValue.Body.userPassword = userPassword;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.dayOfBirth = dayOfBirth;
            inValue.Body.monthOfBirth = monthOfBirth;
            inValue.Body.yearOfBirth = yearOfBirth;
            DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountResponse retVal = ((DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap)(this)).CreateAccount(inValue);
            return retVal.Body.CreateAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountResponse> DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap.CreateAccountAsync(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequest request) {
            return base.Channel.CreateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountResponse> CreateAccountAsync(string email, string userPassword, string firstName, string lastName, int dayOfBirth, int monthOfBirth, int yearOfBirth) {
            DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequest inValue = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequest();
            inValue.Body = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.CreateAccountRequestBody();
            inValue.Body.email = email;
            inValue.Body.userPassword = userPassword;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.dayOfBirth = dayOfBirth;
            inValue.Body.monthOfBirth = monthOfBirth;
            inValue.Body.yearOfBirth = yearOfBirth;
            return ((DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap)(this)).CreateAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsResponse DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap.UserExists(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequest request) {
            return base.Channel.UserExists(request);
        }
        
        public bool UserExists(string userEmail) {
            DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequest inValue = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequest();
            inValue.Body = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequestBody();
            inValue.Body.userEmail = userEmail;
            DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsResponse retVal = ((DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap)(this)).UserExists(inValue);
            return retVal.Body.UserExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsResponse> DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap.UserExistsAsync(DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequest request) {
            return base.Channel.UserExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsResponse> UserExistsAsync(string userEmail) {
            DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequest inValue = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequest();
            inValue.Body = new DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.UserExistsRequestBody();
            inValue.Body.userEmail = userEmail;
            return ((DNP1.ViaCinema.Services.Proxies.ViaCinemaUserService.ViaCinemaUserServiceSoap)(this)).UserExistsAsync(inValue);
        }
    }
}
